##ENVS
#HOST=10.242.1.1

version: "3"
services:
  wetty:
    image: wettyoss/wetty
    restart: unless-stopped
    environment:
      - BASE=/
      - SSHHOST=${HOST}
      - SSH_PORT=22
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 50001:3000
